### ISSUE TITLE
 Run Arduino code examples on T-Watch

### ISSUE THREAD

**Issue by blangus** [merkez-ul-icadat/merkez-ul-icadat.github.io#11]
Code examples: https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library

How to import:
1. Install Arduino IDE
2. Install ESP32 board support: https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/master/docs/arduino-ide/boards_manager.md
3. Download ZIP from above code examples and import into Arduino IDE: "Sketch" -> "Include Library" -> "Add .ZIP Library..."
4. Select TTGO Board: Tools>Board>TTGO-T-Watch
5. Select example: File>Examples>TTGO T-Watch
6. Upload

**Comment by incyi** [comment]
#6 This issue is related
