### ISSUE TITLE
Order a TTGO T-Watch

### ISSUE THREAD

**Issue by incyi** [merkez-ul-icadat/merkez-ul-icadat.github.io#5]
Order the Lilygo® TTGO T-Watch from: https://nl.aliexpress.com/item/33038999162.html?spm=a2g0s.8937460.0.0.1e452e0eNhD7k4

Please order the GPS and LoRa version.

And also please let me know here when it is received.

**Comment by blangus** [comment]
received :).

**Comment by incyi** [comment]
Received !!
